version: "3.8"

services:
    app:
        build:
            context: ./Portfolio
            dockerfile: .docker/php/Dockerfile
        image: laravel-app
        container_name: Portfolio-app
        volumes:
            - ./Portfolio:/var/www
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: Portfolio-nginx
        ports:
            - "8001:80"
        volumes:
            - ./Portfolio:/var/www
            - ./Portfolio/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: Portfolio-mysql
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: Portfolio-db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: Portfolio-phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - db
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
