name: Deploy Portfólio

on:
  push:
    branches: [ main ] # Dispara o deploy sempre que houver push na main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        # Aqui dizemos para o GitHub entrar na pasta Portfolio antes de rodar o composer
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
        working-directory: ./Portfolio 

      - name: Directory Permissions
        run: chmod -R 777 Portfolio/storage Portfolio/bootstrap/cache

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # local-dir indica que queremos enviar o CONTEÚDO da pasta Portfolio
          local-dir: ./Portfolio/ 
          server-dir: ./public_html/
